{
 "title": "job metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "P95 (sec) trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(job_running_time_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Execution Time Distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "job_running_time_seconds_bucket{job_name=\"Squeeze nn\", method=\"syncSqueezeNn\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "The P95 (sec) distribution over 5min",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(job_running_time_seconds_bucket{job_name=\"Go Deep\", method=\"syncGoDeep\"}[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "The increment (count) over past 5min of each bucket",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(job_running_time_seconds_bucket{job_name=\"Go Deep\", method=\"syncGoDeep\"}[5m])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}